import React from 'react';
import {
  Box, Card, CardContent, Typography, Chip, Stack, alpha, Tooltip, IconButton,
  Table, TableBody, TableCell, TableContainer, TableHead, TableRow,
} from '@mui/material';
import DescriptionIcon from '@mui/icons-material/Description';
import DownloadIcon from '@mui/icons-material/Download';
import FolderOpenIcon from '@mui/icons-material/FolderOpen';
import BusinessIcon from '@mui/icons-material/Business';
import { useData } from '../../context/DataContext';

const TYPE_COLORS = {
  quotation: '#D97706',
  proposal: '#714CF7',
  work_order: '#714CF7',
  coc: '#16A34A',
  packing_list: '#7C3AED',
};

const TYPE_LABELS = {
  quotation: 'Quotation',
  proposal: 'Proposal',
  work_order: 'Work Order',
  coc: 'Certificate of Compliance',
  packing_list: 'Packing List',
};

const cardSx = {
  border: '1px solid #E2E8F0', borderRadius: 3, boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
};

export default function DocumentsTab({ project }) {
  const { getCompanyName } = useData();
  const documents = project.documents || [];

  return (
    <Box>
      <Stack direction="row" alignItems="center" spacing={1} sx={{ mb: 1.5 }}>
        <DescriptionIcon sx={{ fontSize: 16, color: '#64748B' }} />
        <Typography sx={{ fontSize: '0.95rem', fontWeight: 700, color: '#0F172A' }}>Project Documents</Typography>
        <Chip label={`${documents.length} document${documents.length !== 1 ? 's' : ''}`} size="small"
          sx={{ bgcolor: '#F5F3FF', color: '#714CF7', fontWeight: 600, fontSize: '0.62rem', height: 20 }} />
      </Stack>

      <Stack direction="row" spacing={2} sx={{ mb: 2.5, p: 1.5, bgcolor: '#F8FAFC', borderRadius: 2, border: '1px solid #E2E8F0' }}>
        <Stack direction="row" spacing={0.75} alignItems="center">
          <BusinessIcon sx={{ fontSize: 13, color: '#94A3B8' }} />
          <Typography sx={{ fontSize: '0.72rem', color: '#64748B' }}>{getCompanyName(project.company_id)}</Typography>
        </Stack>
        <Typography sx={{ fontSize: '0.72rem', color: '#CBD5E1' }}>|</Typography>
        <Typography sx={{ fontSize: '0.72rem', color: '#64748B' }}>{project.project_name || project.name}</Typography>
        {project.project_code && (
          <Chip label={project.project_code} size="small" sx={{ height: 18, fontSize: '0.6rem', fontWeight: 700, fontFamily: 'monospace', bgcolor: '#F5F3FF', color: '#714CF7' }} />
        )}
      </Stack>

      {documents.length === 0 ? (
        <Card elevation={0} sx={{ ...cardSx, textAlign: 'center', py: 6 }}>
          <FolderOpenIcon sx={{ fontSize: 52, color: '#CBD5E1', mb: 1.5 }} />
          <Typography sx={{ fontSize: '0.88rem', fontWeight: 600, color: '#64748B', mb: 0.5 }}>No documents generated yet</Typography>
          <Typography sx={{ fontSize: '0.76rem', color: '#94A3B8', maxWidth: 340, mx: 'auto' }}>
            Documents are automatically generated as you progress through the project lifecycle.
          </Typography>
        </Card>
      ) : (
        <Card elevation={0} sx={cardSx}>
          <TableContainer>
            <Table size="small">
              <TableHead>
                <TableRow sx={{ bgcolor: '#FAFBFC' }}>
                  {['Type', 'Version', 'Status', 'Generated By', 'Date', ''].map(h => (
                    <TableCell key={h} sx={{ fontWeight: 600, fontSize: '0.7rem', color: '#64748B', py: 1.25, borderColor: '#E2E8F0' }}>
                      {h}
                    </TableCell>
                  ))}
                </TableRow>
              </TableHead>
              <TableBody>
                {documents.map((doc) => {
                  const typeColor = TYPE_COLORS[doc.document_type] || '#64748B';
                  return (
                    <TableRow key={doc.id} hover sx={{ '&:hover': { bgcolor: '#FAFBFC' } }}>
                      <TableCell sx={{ py: 1.25, borderColor: '#E2E8F0' }}>
                        <Chip
                          label={TYPE_LABELS[doc.document_type] || doc.document_type}
                          size="small"
                          sx={{ bgcolor: alpha(typeColor, 0.08), color: typeColor, fontWeight: 600, fontSize: '0.65rem', height: 22, border: `1px solid ${alpha(typeColor, 0.15)}` }}
                        />
                      </TableCell>
                      <TableCell sx={{ py: 1.25, borderColor: '#E2E8F0' }}>
                        <Typography sx={{ fontSize: '0.78rem', fontWeight: 600, color: '#1E293B' }}>v{doc.version}</Typography>
                      </TableCell>
                      <TableCell sx={{ py: 1.25, borderColor: '#E2E8F0' }}>
                        <Chip label={doc.status} size="small"
                          sx={{
                            bgcolor: doc.status === 'final' ? '#F0FDF4' : '#F8FAFC',
                            color: doc.status === 'final' ? '#059669' : '#64748B',
                            fontWeight: 600, fontSize: '0.62rem', height: 20,
                            border: `1px solid ${doc.status === 'final' ? '#BBF7D0' : '#E2E8F0'}`,
                          }} />
                      </TableCell>
                      <TableCell sx={{ py: 1.25, borderColor: '#E2E8F0' }}>
                        <Typography sx={{ fontSize: '0.78rem', color: '#475569' }}>{doc.generated_by}</Typography>
                      </TableCell>
                      <TableCell sx={{ py: 1.25, borderColor: '#E2E8F0' }}>
                        <Typography sx={{ fontSize: '0.72rem', color: '#94A3B8' }}>{doc.generated_at}</Typography>
                      </TableCell>
                      <TableCell sx={{ py: 1.25, borderColor: '#E2E8F0' }}>
                        <Tooltip title="Download PDF">
                          <IconButton size="small" sx={{ color: '#714CF7' }}>
                            <DownloadIcon sx={{ fontSize: 16 }} />
                          </IconButton>
                        </Tooltip>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </TableContainer>
        </Card>
      )}
    </Box>
  );
}
